### ISSUE TITLE
Handling deleted files during a bulk put

### ISSUE THREAD

**Issue by bdeetz** [SpectraLogic/ds3_python_sdk#88]
What is the recommended procedure for continuing a bulk put in the situation where a user may delete the file before the file is actually put?

**Comment by rpmoore** [comment]
Is the user deleting the file from the black pearl or from the local system?

**Comment by bdeetz** [comment]
The user is deleting from the local system before the script has time to
finish recursing through the directory.

**Comment by rpmoore** [comment]
Well, there are a couple options.  One is to detect this when attempting to send the file, and then skip it and after you've sent the rest of the files, delete it from black pearl, which will delete it from the job, and allow that job to complete.  The other option is to again attempt to send the rest of the files, and then let the job expire (this takes 24 hours), or truncate the job yourself.  That will behave like you deleted the file manually.  The safest option is the second on where you truncate the job yourself.
